[package]
name = "CO2-sensor"
version = "0.1.0"
authors = ["Mirabellensaft <tanks@ferrous-systems.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
panic-halt  = "0.2"
cortex-m-rt = "0.6.10"
cortex-m    = "=0.5.8"
heapless    = "0.4.0"
nb = "*"

crc_all = "0.2.0"


[dependencies.dwm1001]
version = "0.1.1"
features = ["dev", "rt"]

[dependencies.nrf52832-hal]
version = "0.8.0"

[patch.crates-io.dw1000]
git = "https://github.com/braun-robotics/rust-dw1000"
rev = "036dc67b3147417c49318b840f4d769f8045967e"
